# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gcbY_ma78Al_6LJRpNxAfimIqchMlHe
"""

#importing required libraries
import cv2
import numpy as np
from sklearn.decomposition import PCA
from google.colab import drive
import os

#mounting the google drive
drive.mount("/content/drive/")

# Load few_framed_resized_and_padded_video
video = cv2.VideoCapture('/content/drive/My Drive/SEM 4/CMPE 295B Final Year Project/few_framed_resized_and_padded_video.mp4')

# Get video properties
fps = int(video.get(cv2.CAP_PROP_FPS))
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
num_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
input_size = os.path.getsize('/content/drive/My Drive/SEM 4/CMPE 295B Final Year Project/few_framed_resized_and_padded_video.mp4')

print(fps, width, height, num_frames, input_size)

#list the resized frames
resized_frame = []
i = 0
while True:
    ret, frame = video.read()
    if not ret: break
    if np.sum(frame[:540, :960, :]) == 0: resized_frame.append(i)
    i+=1

print(resized_frame)